sudo: false # See: docs.travis-ci.com/user/migrating-from-legacy

language: android
jdk:
  - oraclejdk8
  - oraclejdk7

notifications:
  irc: irc.freenode.org#feedhenry

branches:
  except:
    - /^FHMOBSDK-.*$/

android:
  components:
  - platform-tools
  - tools
  - build-tools-23.0.1
  - android-22
  - android-23
  - sys-img-armeabi-v7a-android-22
  - extra-google-m2repository
  - extra-android-m2repository


env:
  global:
    - RELEASE_VERSION=$(grep "<version>" fh-android-sdk/pom.xml | tr "\n" ":" | cut -d ':' -f1 | sed s/\<version\>//g| sed s/\"//g| sed s/\<\\/version\>//g | tr -d ' ')
  matrix:
    - ANDROID_SDK=android-23 ANDROID_EMULATOR=android-22 ANDROID_ABI=armeabi-v7a

before_install:
  # Checkout maven-android-sdk-deployer
  - git clone git://github.com/mosabua/maven-android-sdk-deployer.git

  # Install Android in locally Maven repository
  - cd $PWD/maven-android-sdk-deployer/platforms/$ANDROID_SDK
  - mvn install -N --quiet
  - cd -

  # Install locally google-m2repository (including play services aar)
  - cd $PWD/maven-android-sdk-deployer/repositories
  - mvn install --quiet
  - cd -

before_script:
  - echo no | android create avd --force -n test -t $ANDROID_EMULATOR --abi $ANDROID_ABI

script:
  - set -ev
  - mvn clean install -Drelease
  - cd fh-android-sdk-test
  - mvn clean package -DskipTests=true;
  - emulator -avd test -no-skin -no-audio -no-window&
  - wget https://raw.githubusercontent.com/travis-ci/travis-cookbooks/master/community-cookbooks/android-sdk/files/default/android-wait-for-emulator
  - chmod a+x ./android-wait-for-emulator
  - "./android-wait-for-emulator"
  - adb shell input keyevent 82
  - adb shell df
  - adb install target/fh-android-sdk-test-$RELEASE_VERSION.apk
  - mvn android:instrument

before_deploy:
  - mkdir -p $TRAVIS_BUILD_DIR/FHStarterProject/libs
  - cp $TRAVIS_BUILD_DIR/fh-android-sdk/target/fh-android-sdk-$RELEASE_VERSION.jar $TRAVIS_BUILD_DIR/FHStarterProject/libs/
  - zip -9ry $TRAVIS_BUILD_DIR/fh-android-sdk/target/fh-starter-project-$RELEASE_VERSION.zip $TRAVIS_BUILD_DIR/FHStarterProject

deploy:
  provider: releases
  api_key:
    secure: "B2onmjShKQDX2a2aqkLDbZYISvlXpS44f5Xet9MMZD7qFM+UbHYdM4El2seh6mvKLpB8WRv/ss45oEMBw4uXEKD0Rm3Ruk9tFkT35e17bEdYkuGupBr7DK5q6fvi9EVMSqlUDd3OTgQ8iqVN4OnYHsc2bwSxJuQopTpcljsoipg="
  file:
    - $TRAVIS_BUILD_DIR/fh-android-sdk/target/fh-android-sdk-$RELEASE_VERSION.jar
    - $TRAVIS_BUILD_DIR/fh-android-sdk/target/fh-android-sdk-$RELEASE_VERSION.aar
    - $TRAVIS_BUILD_DIR/fh-android-sdk/target/fh-starter-project-$RELEASE_VERSION.zip
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    repo: feedhenry/fh-android-sdk
    jdk: oraclejdk7
